
---

- hosts: all
  tasks:

    - name: Add user cadizm
      user:
        name: cadizm
        group: users
        groups: users,sudo
        shell: /bin/bash
        state: present

    - name: Add cadizm authorized_key
      authorized_key:
        user: cadizm
        key: https://github.com/cadizm.keys

    - name: Set home ownership
      file:
        path: /home/cadizm
        owner: cadizm
        recurse: yes

    - name: Disable root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin\s+.*$'
        line: 'PermitRootLogin no'
      notify:
        - Restart sshd

    - name: Install vim
      apt: name=vim update_cache=yes

    - name: Install git
      apt: name=git update_cache=no

    - name: Install pip
      apt: name=python-pip update_cache=no

    - name: Install python dotfiles
      pip: name=dotfiles

    - name: Create workspace/src directory
      file:
        path: /home/cadizm/workspace/src
        state: directory
        mode: 0755
        owner: cadizm
        group: users

    - name: Check out cadizm dotfiles repo
      git:
        repo: https://github.com/cadizm/dotfiles.git
        dest: /home/cadizm/workspace/src/dotfiles
      notify:
        - Sync dotfiles

    - name: Check out cadizm bin repo
      git:
        repo: https://github.com/cadizm/bin.git
        dest: /home/cadizm/workspace/src/bin
      notify:
        - Link bin dir

  handlers:
    - name: Restart sshd
      service: name=sshd state=restarted

    - name: Sync dotfiles
      command: dotfiles --sync --force --home=/home/cadizm --repo=/home/cadizm/workspace/src/dotfiles
      become_user: cadizm

    - name: Link bin dir
      command: ln -s /home/cadizm/workspace/src/bin /home/cadizm/bin
      become_user: cadizm
